# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, null=True)),
                ('country_subdomain', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='countrystate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200, null=True)),
                ('importance', models.IntegerField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.country')),
            ],
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.country')),
                ('countrystate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.countrystate')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='countrystate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.countrystate'),
        ),
    ]
