# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='countrystate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='countrystate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_subdomain',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='countrystate',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.country'),
        ),
        migrations.DeleteModel(
            name='countrystate',
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.state'),
        ),
        migrations.AddField(
            model_name='publication',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.state'),
        ),
    ]
