# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
