# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('login_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('login_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
